### ISSUE TITLE
Grievances Repo

### ISSUE THREAD

**Issue by kurtlewis** [MemeMagic/todo#2]
Should we make a repo for [airing of grievances](https://www.youtube.com/watch?v=1l8Eag9CAFk)?

We can make issues and have a permanent list of grievances of those grievances that need to down in the history of Github.

ex:
Dom Bailolino didn't show up on Friday 1/20/2017

TBH this is a dumb idea but dom and I got a good laugh out of the idea

**Comment by zcollins0** [comment]
I am pretty sure it's spelled Bailino.

**Comment by ltebben** [comment]
I'm pretty sure it's Bailolino cause we're just replacing the Far- part with Bail- ...
